### PR TITLE
Ensure userId

### PR DESCRIPTION
**Pull request by hankim813**
Resolves https://segment.atlassian.net/browse/INT-710

Heap has been rejecting any `.track()` or `.identify()` events without `userId` and requested that we reject those events at our integration worker level.

From Heap:

## TODO
- [x] deploy site-docs [PR](https://github.com/segmentio/site-docs/pull/1983)
- [x] deploy integration-worker

@tsholmes @f2prateek @sperand-io @jgershen

### CODE REVIEW

**Review by tsholmes — CHANGES_REQUESTED** [review]
I think the version should be `1.0.14` next

**Comment by f2prateek** [comment]
Why not send an anonymous id? How do anonymous users work in heap?

**Comment by hankim813** [comment]
@f2prateek Asked them that question



This problem they said was rooted from mainly mobile events

**Review by tsholmes — APPROVED** [review]
(Pending resolution of Prateek's comment)

Could you re-separate the commits so the release commit is just the changelog and version bump? That way you can rebase merge and have a nice commit history

**Comment by f2prateek** [comment]
@hankim813 not sure it answered my question. How does Heap's mobile SDK handle anonymous users? We should try do the same in the server integration, no?

**Comment by hankim813** [comment]
@f2prateek yep I asked them. So if they were using Heap SDK natively and wanted to send anonymous events server side, they would've had to somehow send the auto generated anonymousId from Heap to the server and send that in order to attribute. Since we do not have a bundleable iOS integration for Heap (and if we did, this PR would not be necessary), these changes should be the safest best bet as of now. We could in theory implement a lookup for Heap ID inside an integration option but that would not be a practical scenario since if a user loaded Heap client side, we would load their client library, which does not have this issue since they auto alias.

If they had an alias server side endpoint, that would be ideal but they do not.

**Comment by f2prateek** [comment]
> somehow send the auto generated anonymousId from Heap to the server

but we already do that with the anonymous ID ourselves. Why not use our anonymousId in place of a userId?

**Comment by hankim813** [comment]
@f2prateek because they create duplicate profiles. If you send anonymousIds then would create a new profile and no other identified events can be associated with those events.

**Comment by f2prateek** [comment]
Ok, but how do they handle anonymous users then? You said they generate an id (we also generate anonymous id) and it doesn't create a duplicate profile.

**Pull request merged**
